dist: trusty
sudo: require
language: cpp
compiler: gcc
os: 
    - linux
    - osx
addons:
  apt:
    sources:
      - sourceline: "ppa:george-edison55/cmake-3.x"
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-7
      - g++-7
      - libglu1-mesa-dev
      - xorg-dev
script:
    - if ["$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - if ["$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - if ["$TRAVIS_OS_NAME" == "linux" ]; then export CC=/usr/bin/gcc-7
    - if ["$TRAVIS_OS_NAME" == "linux" ]; then export CXX=/usr/bin/g++-7
    - gcc -v && g++ -v && cmake --version
    - git --version
    # setup and check fips
    - git clone https://github.com/floooh/fips.git ../fips
    # build
    - python fips gen
    - python fips list targets
    - python fips build
    # run tests
    - python fips run crTest
